# --- execute positions ---
execute at @p run particle flame # at ...
execute positioned 0 0 0 run particle flame # positioned ...
execute align xyz run particle flame # align ...
execute rotated as @p run particle flame # rotated as ...